### ISSUE TITLE
Road to V1 !

### ISSUE THREAD

**Issue by Ked57** [Ked57/NIOD#2]
Big change in what NIOD in going to do ! We will now use MOOSE, this is gonna make the LUA much easier and since I already like a lot what the MOOSE team does we might as well use their hard work !

So this is what is left to do for V1

- [x] A NodeJS package to run and extend the Niod server (kind of what express does for http servers) 
    - [x] Start Niod with a simple function
- [x] Spawning groups from template
- [x] Getting information on zones and integrate it with spawning
- [x] Make the socket connection a little more resilient (retries on disconections)
- [x] Basic triggers: partial and complete zone entering for groups
- [x] Documentation of course !

**Comment by Ked57** [comment]
Looks like we're ready for release !
